// products.js — Shopler catalogue. Loaded via <script>, sets window.PRODUCTS.
// No build step. SKUs must remain stable — recommendation logic keys on .id.
'use strict';
window.PRODUCTS = [
  // ── COATS ───────────────────────────────────────────────────────────────────
  {
    id: 'AO-W-005', name: 'Atelier Ode Wool-blend Coat', brand: 'Atelier Ode',
    category: 'Coats', colour: 'Camel', material: 'Wool blend',
    price: 119.95, sale_price: null, stock: 4, in_stock: true, popularity: 88,
    sizes: ['S','M','L','XL'],
    pairs_with: ['NR-W-002','AO-W-002','AO-A-001','NR-K-001'],
    img_color: '#c8a96e',
  },
  {
    id: 'NR-W-001', name: 'Noreen Classic Wool Coat', brand: 'Noreen',
    category: 'Coats', colour: 'Black', material: 'Wool',
    price: 39.95, sale_price: null, stock: 15, in_stock: true, popularity: 72,
    sizes: ['XS','S','M','L'],
    pairs_with: ['NR-T-001','NR-B-001','NR-K-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'NR-W-002', name: 'Noreen Fitted Coat', brand: 'Noreen',
    category: 'Coats', colour: 'Navy', material: 'Polyester blend',
    price: 44.95, sale_price: null, stock: 8, in_stock: true, popularity: 68,
    sizes: ['S','M','L','XL'],
    pairs_with: ['NR-K-003','NR-T-002'],
    img_color: '#1a2b5e',
  },
  {
    id: 'NR-W-003', name: 'Noreen Winter Coat', brand: 'Noreen',
    category: 'Coats', colour: 'Beige', material: 'Wool blend',
    price: 34.95, sale_price: null, stock: 11, in_stock: true, popularity: 65,
    sizes: ['XS','S','M'],
    pairs_with: ['NR-K-002','NR-B-002'],
    img_color: '#e8d9c0',
  },
  {
    id: 'NR-W-004', name: 'Noreen Slim-line Coat', brand: 'Noreen',
    category: 'Coats', colour: 'Forest Green', material: 'Polyester',
    price: 42.95, sale_price: null, stock: 6, in_stock: true, popularity: 58,
    sizes: ['S','L','XL'],
    pairs_with: ['NR-T-001'],
    img_color: '#2d5a3d',
  },
  {
    id: 'NR-W-005', name: 'Noreen Everyday Coat', brand: 'Noreen',
    category: 'Coats', colour: 'Bordeaux', material: 'Wool blend',
    price: 37.95, sale_price: null, stock: 9, in_stock: true, popularity: 62,
    sizes: ['XS','S','L'],
    pairs_with: ['NR-K-001'],
    img_color: '#7b1c3a',
  },
  {
    id: 'AO-W-001', name: 'Atelier Ode Cashmere Coat', brand: 'Atelier Ode',
    category: 'Coats', colour: 'Ivory', material: 'Cashmere',
    price: 149.95, sale_price: null, stock: 5, in_stock: true, popularity: 71,
    sizes: ['XS','S','M'],
    pairs_with: ['AO-A-001','AO-B-001'],
    img_color: '#f4f0e8',
  },
  {
    id: 'AO-W-002', name: 'Atelier Ode Oversized Coat', brand: 'Atelier Ode',
    category: 'Coats', colour: 'Charcoal', material: 'Wool',
    price: 134.95, sale_price: null, stock: 7, in_stock: true, popularity: 69,
    sizes: ['S','M','L'],
    pairs_with: ['AO-A-001'],
    img_color: '#4a4a4a',
  },
  {
    id: 'AO-W-003', name: 'Atelier Ode Belted Coat', brand: 'Atelier Ode',
    category: 'Coats', colour: 'Camel', material: 'Cashmere blend',
    price: 124.95, sale_price: null, stock: 3, in_stock: true, popularity: 74,
    sizes: ['S','M','L','XL'],
    pairs_with: ['AO-A-001'],
    img_color: '#c8a96e',
  },
  {
    id: 'AO-W-004', name: 'Atelier Ode Tailored Coat', brand: 'Atelier Ode',
    category: 'Coats', colour: 'Black', material: 'Wool',
    price: 139.95, sale_price: null, stock: 9, in_stock: true, popularity: 66,
    sizes: ['XS','S','M'],
    pairs_with: ['AO-B-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'EL-W-001', name: 'Eleganza Trench Coat', brand: 'Eleganza',
    category: 'Coats', colour: 'Sand', material: 'Cotton blend',
    price: 89.95, sale_price: null, stock: 12, in_stock: true, popularity: 61,
    sizes: ['S','M','L','XL'],
    pairs_with: ['EL-T-001'],
    img_color: '#d4c4a0',
  },
  {
    id: 'CL-W-001', name: 'Clara Luxe Coat', brand: 'Clara',
    category: 'Coats', colour: 'Taupe', material: 'Viscose blend',
    price: 99.95, sale_price: null, stock: 6, in_stock: true, popularity: 63,
    sizes: ['S','M','L'],
    pairs_with: [],
    img_color: '#b0a090',
  },

  // ── KNITWEAR ─────────────────────────────────────────────────────────────────
  {
    id: 'NR-K-001', name: 'Noreen Merino Rollneck', brand: 'Noreen',
    category: 'Knitwear', colour: 'Black', material: 'Merino wool',
    price: 34.95, sale_price: null, stock: 20, in_stock: true, popularity: 75,
    sizes: ['XS','S','M','L','XL'],
    pairs_with: ['NR-W-001','NR-T-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'NR-K-002', name: 'Noreen Cable Knit', brand: 'Noreen',
    category: 'Knitwear', colour: 'Cream', material: 'Wool blend',
    price: 29.95, sale_price: null, stock: 18, in_stock: true, popularity: 71,
    sizes: ['XS','S','M','L','XL'],
    pairs_with: ['NR-W-003'],
    img_color: '#f5f2e8',
  },
  {
    id: 'NR-K-003', name: 'Noreen V-neck Pullover', brand: 'Noreen',
    category: 'Knitwear', colour: 'Navy', material: 'Cotton mix',
    price: 31.95, sale_price: null, stock: 15, in_stock: true, popularity: 67,
    sizes: ['XS','S','M','L'],
    pairs_with: ['NR-W-002','NR-T-002'],
    img_color: '#1a2b5e',
  },
  {
    id: 'AO-K-001', name: 'Atelier Ode Cashmere Pullover', brand: 'Atelier Ode',
    category: 'Knitwear', colour: 'Camel', material: 'Cashmere',
    price: 89.95, sale_price: null, stock: 6, in_stock: true, popularity: 64,
    sizes: ['XS','S','M','L'],
    pairs_with: ['AO-W-005','AO-W-002'],
    img_color: '#c8a96e',
  },
  {
    id: 'EL-K-001', name: 'Eleganza Fine-knit Cardigan', brand: 'Eleganza',
    category: 'Knitwear', colour: 'Dusty Rose', material: 'Acrylic blend',
    price: 49.95, sale_price: null, stock: 11, in_stock: true, popularity: 58,
    sizes: ['S','M','L','XL'],
    pairs_with: ['EL-D-001'],
    img_color: '#d4a0a0',
  },
  {
    id: 'MI-K-001', name: 'Milano Chunky Knit', brand: 'Milano',
    category: 'Knitwear', colour: 'Ecru', material: 'Acrylic',
    price: 54.95, sale_price: null, stock: 8, in_stock: true, popularity: 55,
    sizes: ['S','M','L'],
    pairs_with: [],
    img_color: '#f0e8d0',
  },

  // ── DRESSES ──────────────────────────────────────────────────────────────────
  {
    id: 'NR-D-001', name: 'Noreen Midi Dress', brand: 'Noreen',
    category: 'Dresses', colour: 'Black', material: 'Viscose',
    price: 44.95, sale_price: 34.95, stock: 13, in_stock: true, popularity: 70,
    sizes: ['XS','S','M','L'],
    pairs_with: ['NR-K-001','NR-J-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'NR-D-002', name: 'Noreen Wrap Dress', brand: 'Noreen',
    category: 'Dresses', colour: 'Forest Green', material: 'Jersey',
    price: 39.95, sale_price: null, stock: 9, in_stock: true, popularity: 66,
    sizes: ['XS','S','M','L'],
    pairs_with: ['NR-K-002'],
    img_color: '#2d5a3d',
  },
  {
    id: 'AO-D-001', name: 'Atelier Ode Silk Dress', brand: 'Atelier Ode',
    category: 'Dresses', colour: 'Ivory', material: 'Silk',
    price: 129.95, sale_price: null, stock: 4, in_stock: true, popularity: 62,
    sizes: ['XS','S','M'],
    pairs_with: ['AO-A-001'],
    img_color: '#f4f0e8',
  },
  {
    id: 'EL-D-001', name: 'Eleganza Shift Dress', brand: 'Eleganza',
    category: 'Dresses', colour: 'Navy', material: 'Crepe',
    price: 74.95, sale_price: null, stock: 7, in_stock: true, popularity: 57,
    sizes: ['S','M','L'],
    pairs_with: ['EL-K-001'],
    img_color: '#1a2b5e',
  },

  // ── BLOUSES & TOPS ───────────────────────────────────────────────────────────
  {
    id: 'NR-B-001', name: 'Noreen Silk Blouse', brand: 'Noreen',
    category: 'Tops', colour: 'Black', material: 'Satin',
    price: 29.95, sale_price: null, stock: 22, in_stock: true, popularity: 74,
    sizes: ['XS','S','M','L','XL'],
    pairs_with: ['NR-W-001','NR-T-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'NR-B-002', name: 'Noreen Satin Top', brand: 'Noreen',
    category: 'Tops', colour: 'Navy', material: 'Satin',
    price: 27.95, sale_price: null, stock: 17, in_stock: true, popularity: 68,
    sizes: ['XS','S','M','L'],
    pairs_with: ['NR-W-003'],
    img_color: '#1a2b5e',
  },
  {
    id: 'AO-B-001', name: 'Atelier Ode Crepe Blouse', brand: 'Atelier Ode',
    category: 'Tops', colour: 'Ivory', material: 'Crepe',
    price: 84.95, sale_price: null, stock: 8, in_stock: true, popularity: 60,
    sizes: ['XS','S','M','L'],
    pairs_with: ['AO-W-001','AO-W-004'],
    img_color: '#f4f0e8',
  },
  {
    id: 'EL-B-001', name: 'Eleganza Print Blouse', brand: 'Eleganza',
    category: 'Tops', colour: 'Dusty Rose', material: 'Polyester',
    price: 44.95, sale_price: null, stock: 12, in_stock: true, popularity: 56,
    sizes: ['S','M','L','XL'],
    pairs_with: [],
    img_color: '#d4a0a0',
  },

  // ── TROUSERS ─────────────────────────────────────────────────────────────────
  {
    id: 'NR-T-001', name: 'Noreen Wide-leg Trousers', brand: 'Noreen',
    category: 'Trousers', colour: 'Black', material: 'Viscose blend',
    price: 37.95, sale_price: null, stock: 16, in_stock: true, popularity: 72,
    sizes: ['XS','S','M','L','XL'],
    pairs_with: ['NR-W-001','NR-B-001','NR-K-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'NR-T-002', name: 'Noreen Tailored Trousers', brand: 'Noreen',
    category: 'Trousers', colour: 'Navy', material: 'Polyester',
    price: 42.95, sale_price: null, stock: 11, in_stock: true, popularity: 65,
    sizes: ['XS','S','M','L'],
    pairs_with: ['NR-W-002','NR-K-003'],
    img_color: '#1a2b5e',
  },
  {
    id: 'AO-T-001', name: 'Atelier Ode Crepe Trousers', brand: 'Atelier Ode',
    category: 'Trousers', colour: 'Camel', material: 'Crepe',
    price: 79.95, sale_price: null, stock: 7, in_stock: true, popularity: 58,
    sizes: ['XS','S','M','L'],
    pairs_with: ['AO-B-001'],
    img_color: '#c8a96e',
  },
  {
    id: 'EL-T-001', name: 'Eleganza Flare Trousers', brand: 'Eleganza',
    category: 'Trousers', colour: 'Olive', material: 'Cotton',
    price: 54.95, sale_price: null, stock: 9, in_stock: true, popularity: 54,
    sizes: ['S','M','L','XL'],
    pairs_with: ['EL-W-001'],
    img_color: '#6b7c3d',
  },

  // ── BLAZERS & JACKETS ────────────────────────────────────────────────────────
  {
    id: 'NR-J-001', name: 'Noreen Classic Blazer', brand: 'Noreen',
    category: 'Blazers', colour: 'Black', material: 'Polyester blend',
    price: 44.95, sale_price: null, stock: 13, in_stock: true, popularity: 73,
    sizes: ['XS','S','M','L','XL'],
    pairs_with: ['NR-T-001','NR-D-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'AO-J-001', name: 'Atelier Ode Structured Blazer', brand: 'Atelier Ode',
    category: 'Blazers', colour: 'Ivory', material: 'Viscose',
    price: 109.95, sale_price: null, stock: 5, in_stock: true, popularity: 65,
    sizes: ['XS','S','M'],
    pairs_with: ['AO-T-001'],
    img_color: '#f4f0e8',
  },
  {
    id: 'EL-J-001', name: 'Eleganza Biker Jacket', brand: 'Eleganza',
    category: 'Blazers', colour: 'Black', material: 'Faux leather',
    price: 94.95, sale_price: null, stock: 4, in_stock: true, popularity: 60,
    sizes: ['S','M','L'],
    pairs_with: ['EL-T-001'],
    img_color: '#2d2d2d',
  },
  {
    id: 'MI-J-001', name: 'Milano Denim Jacket', brand: 'Milano',
    category: 'Blazers', colour: 'Indigo', material: 'Denim',
    price: 64.95, sale_price: null, stock: 11, in_stock: true, popularity: 57,
    sizes: ['S','M','L','XL'],
    pairs_with: [],
    img_color: '#2d3b8e',
  },

  // ── ACCESSORIES ──────────────────────────────────────────────────────────────
  {
    id: 'NR-A-001', name: 'Noreen Wool Scarf', brand: 'Noreen',
    category: 'Accessories', colour: 'Black', material: 'Wool',
    price: 19.95, sale_price: null, stock: 25, in_stock: true, popularity: 66,
    sizes: ['One size'],
    pairs_with: ['NR-W-001','NR-W-002'],
    img_color: '#2d2d2d',
  },
  {
    id: 'AO-A-001', name: 'Atelier Ode Leather Belt', brand: 'Atelier Ode',
    category: 'Accessories', colour: 'Camel', material: 'Leather',
    price: 44.95, sale_price: null, stock: 8, in_stock: true, popularity: 55,
    sizes: ['S/M','L/XL'],
    pairs_with: ['AO-W-005','AO-W-003','AO-W-001'],
    img_color: '#c8a96e',
  },
  {
    id: 'CL-A-001', name: 'Clara Beaded Necklace', brand: 'Clara',
    category: 'Accessories', colour: 'Gold', material: 'Brass',
    price: 34.95, sale_price: null, stock: 15, in_stock: true, popularity: 52,
    sizes: ['One size'],
    pairs_with: [],
    img_color: '#c8a030',
  },
];
